# agent/state.py

from typing import Dict, Any, List, Optional, Annotated
from pydantic import BaseModel, Field
from langgraph.graph.message import add_messages
from schemas.analysis_models import InvestigationLedger


class AgentState(BaseModel):
    """
    The Single Source of Truth for the Graph.
    Includes the 'Ledger' (Structured Context) and 'Messages' (Chat History).
    """

    # --- CORE CONFIGURATION ---
    repo_path: str = Field(".", description="Root path of the target repository")
    verbose: bool = Field(False, description="Enable debug logging")

    # --- INGESTION PHASE DATA ---
    manifest: List[Dict[str, Any]] = Field(default_factory=list, description="File listing and metadata")
    priority_files: List[str] = Field(default_factory=list, description="High-signal files like README, requirements.txt")
    
    # CRITICAL: This now holds the "Visual Tree" generated by ingestion.py
    structure_map: str = Field("", description="Visual Directory Tree + Python Code Skeleton")
    
    project_summary: str = Field("", description="High-level description generated by Recon")
    
    # --- REGEX INTELLIGENCE (NEW) ---
    regex_findings: str = Field("", description="Summary of high-confidence patterns found during Recon.")

    search_plan: List[str] = Field(default_factory=list, description="Initial strategy")

    # --- THE SNOWBALL (Ledger) ---
    # This is the structured brain passed from Architect -> Intelligence -> Integrator
    ledger: InvestigationLedger = Field(default_factory=InvestigationLedger)

    # --- ROUTING CONTROL ---
    # Options: "architect" | "intelligence" | "integrator"
    active_specialist: str = Field("architect")

    # --- USER CONTEXT ---
    pricing_context: str = Field("", description="Accumulated user inputs regarding traffic/pricing")

    # --- CHAT HISTORY ---
    messages: Annotated[List[Any], add_messages] = Field(default_factory=list)

    # --- FINAL OUTPUT ---
    final_report: Dict[str, Any] = Field(default_factory=dict)
    
    # --- FUZZY PARSE GUARD (NEW) ---
    fuzzy_parse_count: int = Field(0, description="Counter to prevent infinite fuzzy parsing loops")

    class Config:
        arbitrary_types_allowed = True
